server:
  port: 8080

spring:
  profiles:
    active:
      - dev
  application:
    name: GATEWAY-SERVICE

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8079/eureka
    initial-instance-info-replication-interval-seconds: 30
    registry-fetch-interval-seconds: 30

  instance:
    preferIpAddress: true
    instanceId: ${spring.application.name}